import type { AnalysisResult } from "../analyze";

export function exportAsMarkdown(result: AnalysisResult): string {
  const { job, match, coverLetter, interviewQuestions, linkedin } = result;

  return `# Application Analysis: ${job.jobTitle}${job.company ? ` at ${job.company}` : ""}

## Match Score: ${match.matchScore}%

**Verdict:** ${match.matchLabel}

${match.matchSummary}

**Required coverage:** ${match.requiredCoverage}%

### Why this verdict was given
${match.reasons.map((reason) => `- ${reason}`).join("\n") || "_No structured reasons available_"}

> This is an evidence-alignment assessment, not proof that the candidate can perform the role. Experience, licences and eligibility still require verification.

### Matched Skills
${match.matchedSkills.map((m) => `- ${m.skill} (${m.confidence} confidence)`).join("\n") || "_None found_"}

### Missing Skills
${match.missingSkills.map((s) => `- ${s}`).join("\n") || "_None — full coverage_"}

### Weak Evidence
${match.weakEvidence.map((w) => `- ${w.skill}: ${w.reason}`).join("\n") || "_None_"}

---

## Cover Letter (${coverLetter.mode === "llm" ? "provider-assisted evidence selection" : "template-drafted"})

${coverLetter.letter}

### Blocked Claims
${coverLetter.blockedClaims.length > 0 ? coverLetter.blockedClaims.map((c) => `- ${c} — no supporting evidence found, not included above`).join("\n") : "_None — every required skill had supporting evidence_"}

---

## Interview Prep

### Technical
${interviewQuestions.technical.map((q) => `- ${q}`).join("\n")}

### Behavioural
${interviewQuestions.behavioural.map((q) => `- ${q}`).join("\n")}

### Questions to Ask the Employer
${interviewQuestions.toAskEmployer.map((q) => `- ${q}`).join("\n")}

---

## LinkedIn Suggestions

**Headline:** ${linkedin.headline}

**About section points:**
${linkedin.aboutSectionPoints.map((p) => `- ${p}`).join("\n") || "_Add more detailed CV content for suggestions_"}

**Skills to add:** ${linkedin.skillsToAdd.join(", ") || "None"}

---

_Generated by JobPilot AI. Claims are limited to the evidence supplied, but every result still requires human review._
`;
}
